# Generated by Django 5.1.5 on 2025-02-04 14:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={"verbose_name": "Wallet", "verbose_name_plural": "Wallets"},
        ),
        migrations.AddField(
            model_name="wallet",
            name="farcaster_handle",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="portfolio",
            field=models.JSONField(
                default={"alts": 25, "majors": 25, "memes": 25, "stables": 25},
                validators=[core.models.validate_portfolio_sum],
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="twitter_handle",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
