# Generated by Django 5.1.5 on 2025-02-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_wallet_options_wallet_farcaster_handle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAJORS", "Major currencies"),
                            ("STABLES", "Stablecoins"),
                            ("ALTS", "Altcoins"),
                            ("MEMES", "Memecoins"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "coingecko_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("alchemy_id", models.CharField(blank=True, max_length=50, null=True)),
                ("chain_id", models.IntegerField()),
                (
                    "alchemy_chain_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "coingecko_chain_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("decimals", models.IntegerField()),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("market_data", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "db_table": "tokens",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="wallet",
            name="chain_id",
            field=models.IntegerField(default=8453),
        ),
        migrations.CreateModel(
            name="WalletToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.FloatField(default=0)),
                ("balance_usd", models.FloatField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.token"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.wallet"
                    ),
                ),
            ],
            options={
                "db_table": "wallet_tokens",
                "unique_together": {("wallet", "token")},
            },
        ),
        migrations.AddField(
            model_name="token",
            name="wallets",
            field=models.ManyToManyField(
                related_name="tokens", through="core.WalletToken", to="core.wallet"
            ),
        ),
    ]
