# Generated by Django 5.1.6 on 2025-02-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_token_wallet_chain_id_wallettoken_token_wallets"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="latest_trade_summary",
            field=models.JSONField(
                blank=True,
                help_text="Armazena o resumo do trade mais recente desta carteira",
                null=True,
            ),
        ),
    ]
