# Generated by Django 5.1.6 on 2025-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_wallet_latest_trade_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="farcaster_handle",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="twitter_handle",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
