# Generated by Django 5.1.6 on 2025-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_wallet_farcaster_handle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlchemyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="core_alchem_event_i_5e92fb_idx"
                    )
                ],
            },
        ),
    ]
